platform :ios, '9.0'

use_frameworks!

target 'emojidataios_Example' do
  pod 'emojidataios', :path => '../'

  target 'emojidataios_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 2.1.0'
  pod 'Nimble', '~> 8.0.1'
  end
end
