platform :ios, '9.0'

use_frameworks!

target 'emojidataios_Example' do
  pod 'emojidataios', :path => '../'

  target 'emojidataios_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.3.2'
  pod 'Nimble', '~> 7.3.1'
  end
end
